name: NorwayOutlinesPopulator
version: '1.0'
main: no.agentorw.norwayOutlinesPopulator.NorwayOutlinesPopulator
api-version: '1.21'
author: agentORW
description: A plugin that populates Norway with building and road data.
load: STARTUP